### ISSUE TITLE
Konventionen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/forhtml#1]
Für'n PR hätte ich zunächst Vorschläge zu Konventionen:

`fragments/[addon/]framework/typ.fall.php`

z.B.
`fragments/bootstrap5/template.default.php`
`fragments/bootstrap5/template.blog.php`
`fragments/qanda/bootstrap5/list.php`
`fragments/qanda/bootstrap5/details.php`

Dann könnte ich eine Handvoll Fragmente für Bootstrap 5 zur Verfügung stellen - vielleicht willst du ja aber auch was eigenes machen.

**Comment by skerbis** [comment]
Ja gerne mitmachen. Guter Idee wird so umgesetzt

**Comment by skerbis** [comment]
@alxndr-w 
- die Fragmente werden alle eine Hilfe in Form eines Arrays erhalten. 
Ich denke das kannst du gut im jetzigen Fragment erkennen. 

Bei uikit werden die Fragmente den componenten-Namen von uikit erhalten also wie hier beim ersten uk_card.php

Beispiele: 
uk_container
uk_section
uk_slideshow
uk_slider
uk_tile
uk_countdown

Das soll Nutzern die uikit kennen schneller das richtige Fragment zu finden. 
Gerne bitte das auch so für Bootstrap machen

**Comment by alxndr-w** [comment]
Es wäre denkbar, ja Komponenten und Fragmente zueinander kompatibel zu halten. Framework wechseln = Verzeichnis wechseln = fertig

**Comment by skerbis** [comment]
Spannend

**Comment by skerbis** [comment]
aber du hast Recht durch die Unterordner braucht man das uk_ nicht

**Comment by alxndr-w** [comment]
Ich habe die einzelnen Komponenten bisher mit `atom.` gekennzeichnet, da bei mir haupts. Module eingesetzt werden, aber ich schaue mal, was sich machen lässt.

![image](https://user-images.githubusercontent.com/3855487/197402362-3ca8661d-f84d-44e4-9129-58ee1e430ccb.png)

**Comment by skerbis** [comment]
Mein Ansatz ist Komponenten zu liefern egal ob für Module, Addons oder Templates, möglichst flexibel.

**Comment by skerbis** [comment]
Hier geht es weiter: https://github.com/FriendsOfREDAXO/mfragment
